server:
  port: 8080
mpesa:
  daraja:
    consumer-key: 1GPYLyTvmQDDLe8Qw9K4DUapiZzdTME2arB6vKYV1DJEQH88
    consumer-secret: uZa9mt29q6NAnIKMfiyFZJarsttT8W39qZJqUXBvw8zbnaQIGaWlL3LLTAh6QZKy
    grant-type: client_credentials
    oauth-endpoint: https://sandbox.safaricom.co.ke/oauth/v1/generate
    register-url-endpoint: https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl
    simulate-transaction-endpoint: https://sandbox.safaricom.co.ke/mpesa/c2b/v1/simulate
    shortCode: 603021
    confirmationURL: https://e043-102-210-244-74.ngrok-free.app/mobile-money/confirmation
    validationURL: https://e043-102-210-244-74.ngrok-free.app/mobile-money/validation
    responseType: Completed
    b2c-transaction-endpoint: https://sandbox.safaricom.co.ke/mpesa/b2c/v1/paymentrequest
    b2c-result-url: https://e043-102-210-244-74.ngrok-free.app/mobile-money/transaction-result
    b2c-queue-timeout-url: https://e043-102-210-244-74.ngrok-free.app/mobile-money/b2c-queue-timeout
    b2c-initiator-name: apiop37
    b2c-initiator-password: Safaricom3021#
    transactionResultUrl: https://sandbox.safaricom.co.ke/mpesa/transactionstatus/v1/query
    checkAccountBalanceUrl: https://sandbox.safaricom.co.ke/mpesa/accountbalance/v1/query
    stkPassKey: bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
    stkPushShortCode: 174379
    stkPushRequestUrl: https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest
    stkPushRequestCallbackUrl: https://e043-102-210-244-74.ngrok-free.app/mobile-money/stk-transaction-result
    lnmQueryRequestUrl: https://sandbox.safaricom.co.ke/mpesa/stkpushquery/v1/query
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: daraja-db